services:
  - type: web
    name: telegraph-bot
    env: node
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: TELEGRAPH_ACCESS_TOKEN
        value: e381330fb7dd5130dea695b5930071d4aede79248752ad2e05e2f2b34355
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3000
      - key: NODE_ENV
        value: production
